from KP.Distribution import *
from KP.Function import Function
from KP.Terminal import Terminal

Term1 = Terminal(100, 20)
Term2 = Terminal(100, 20)
Term3 = Terminal(100, 20)
Term4 = Terminal(100, 20)

listFunctions = []
listTerminals = []

BDP = Function(20, ["IW2E", "IW2'E", "IW1E", "IT1E", "IT2E", "I1QCE", "I2QCE", "TV1E", "TV2E"], "main", "BUSE")
DZL1 = Function(15, ["IW2E", "DZL1'"], "main", "W2E")
DZL2 = Function(15, ["IW2'E", "DZL2'"], "main", "W2'E")
DZL3 = Function(15, ["IW1E", "DZL3'"], "main", "W1E")
KSZ1 = Function(10, ["IW2E", "TV1E"], "secondary", "W2E")
KSZ2 = Function(10, ["IW2'E", "TV2E"], "secondary", "W2'E")
KSZ3 = Function(10, ["IW1E", "TV1E"], "secondary", "W1E")
KSZ4 = Function(10, ["I1QCE", "TV1E", "TV2E"], "secondary", "QCE")
KSZ5 = Function(10, ["IT1E", "TV1E", "IT1K", "TV1K"], "secondary", "T1")
KSZ6 = Function(10, ["IT2E", "TV2E", "IT2K", "TV2K"], "secondary", "T2")
TDP1 = Function(15, ["IT1E", "IT1K"], "main", "T1")
TDP2 = Function(15, ["IT2E", "IT2K"], "main", "T2")
KSZ7 = Function(5, ["I1QCK", "TV1K", "TV2K"], "main", "QCK")
KSZ8 = Function(5, ["IW1K", "TV1K"], "main", "W1K")
KSZ9 = Function(5, ["IW2K", "TV1K"], "main", "W2K")
KSZ10 = Function(5, ["IW3K", "TV1K"], "main", "W3K")
KSZ11 = Function(5, ["IW4K", "TV1K"], "main", "W4K")
KSZ12 = Function(5, ["IW5K", "TV1K"], "main", "W5K")
KSZ13 = Function(5, ["IW6K", "TV1K"], "main", "W6K")
KSZ14 = Function(5, ["IW7K", "TV2K"], "main", "W7K")
KSZ15 = Function(5, ["IW8K", "TV2K"], "main", "W8K")
KSZ16 = Function(5, ["IW9K", "TV2K"], "main", "W9K")
KSZ17 = Function(5, ["IW10K", "TV2K"], "main", "W10K")
KSZ18 = Function(5, ["IW11K", "TV2K"], "main", "W11K")
KSZ19 = Function(5, ["IW12K", "TV2K"], "main", "W12K")
KSZ20 = Function(5, ["IT1K", "TV1K"], "main", "T1K")
KSZ21 = Function(5, ["IT2K", "TV2K"], "main", "T2K")

listTerminals.append(Term1)
listTerminals.append(Term2)
listTerminals.append(Term3)
listTerminals.append(Term4)

listFunctions.append(BDP)
listFunctions.append(DZL1)
listFunctions.append(DZL2)
listFunctions.append(DZL3)
listFunctions.append(KSZ1)
listFunctions.append(KSZ2)
listFunctions.append(KSZ3)
listFunctions.append(KSZ4)
listFunctions.append(KSZ5)
listFunctions.append(KSZ6)
listFunctions.append(TDP1)
listFunctions.append(TDP2)
listFunctions.append(KSZ7)
listFunctions.append(KSZ8)
listFunctions.append(KSZ9)
listFunctions.append(KSZ10)
listFunctions.append(KSZ11)
listFunctions.append(KSZ12)
listFunctions.append(KSZ13)
listFunctions.append(KSZ14)
listFunctions.append(KSZ15)
listFunctions.append(KSZ16)
listFunctions.append(KSZ17)
listFunctions.append(KSZ18)
listFunctions.append(KSZ19)
listFunctions.append(KSZ20)
listFunctions.append(KSZ21)

process_pack(listTerminals, listFunctions)

# process(listTerminals, listFunctions)

print("Term1")
print([i.equipment + " " + i.appointment for i in Term1.functions if isinstance(i, Function)])
print(sum(Term1.functions_capacity))
print(len(Term1.functions_streams))
print("Term2")
print([i.equipment + " " + i.appointment for i in Term2.functions if isinstance(i, Function)])
print(sum(Term2.functions_capacity))
print(len(Term2.functions_streams))
print("Term3")
print([i.equipment + " " + i.appointment for i in Term3.functions if isinstance(i, Function)])
print(sum(Term3.functions_capacity))
print(len(Term3.functions_streams))
print("Term4")
print([i.equipment + " " + i.appointment for i in Term4.functions if isinstance(i, Function)])
print(sum(Term4.functions_capacity))
print(len(Term4.functions_streams))
